Develop
eunicezhou/Wehelp_Stage2 pull request #7
Opened 2023-09-22 12:13 UTC by eunicezhou

老師:
我是紫珍，這是我week4的作業
測試網址:http://52.198.121.57:3000

2023-09-22 19:49 UTC, cwpeng requested changes
1. We should reject repeated email in sign up procedure.
2. We should call get current user API to check user sign-in status, and show corresponding text on the navigator bar.

2023-09-23 03:06 UTC, eunicezhou commented
老師:
已修改完成，修改內容如下:
1.在nav部分加入登入後的使用者名稱
2.重新修改註冊路徑，拒絕重複的email資料進行註冊

2023-09-23 06:18 UTC, cwpeng requested changes
We should **call get current user API** to check user sign-in status, and show corresponding text on the navigator bar.

2023-09-23 09:30 UTC, eunicezhou commented
老師:
我有修改在每一次刷新頁面的時候都會重新get api，再麻煩您幫我看看

2023-09-23 12:31 UTC, cwpeng requested changes
We should call get current user API to **check user sign-in status**, and show corresponding text on the navigator bar. It means sign-in status of a user should based on API response, not your record in localStorage. Fix it and figure out why we should follow this working flow.

2023-09-23 16:37 UTC, eunicezhou commented
老師:
我理解您的意思了
這次修改程式碼的方向:
在使用者登入時，使用put方法連到api/user/auth，建立出token放到localstorage中，再進行網頁reload
第二次reload檢查localstorage中是否存在token，若有則使用get方法將token進行解碼，得到使用者資訊

這是我的理解，這次的修改有將程式邏輯理清，再麻煩您幫我看一次

2023-09-23 17:39 UTC, cwpeng approved these changes
OK. Done.

2023-09-23 18:18 UTC, merged